### ISSUE TITLE
Doesn't work with Astro 4

### ISSUE THREAD

**Issue by keturiosakys** [HiDeoo/starlight-openapi#16] opened 2023-12-12 13:51 UTC
### Describe the bug

Looks like `starlight-openapi` is broken on Astro 4. 

The errors thrown are:
1. `TypeError: Cannot read properties of undefined (reading 'themeSelect.accessibleLabel')` in dev server
2. `TypeError: Cannot read properties of undefined (reading 'tableOfContents.onThisPage')` on `build`

### To Reproduce

Here's a repro stackblitz+repo: https://stackblitz.com/~/github.com/keturiosakys/starlight-openapi-repro

1. Spin up the dev server
2. Side bar is generated successfully, however, navigating to one of the links crashes the server
3. Server throws: `TypeError: Cannot read properties of undefined (reading 'themeSelect.accessibleLabel')`

Alternatively:
1. Run `pnpm build`
2. The build fails with `TypeError: Cannot read properties of undefined (reading 'tableOfContents.onThisPage')` error

### Expected behavior

Generated pages should open normally.

### How often does this bug happen?

Every time

### Additional Context

Happy to provide a PR for a fix, so continuing to investigate this further. If there are any leads I should take a look at, lmk!

**Comment by HiDeoo** [comment] 2023-12-12 19:34
Thanks for the report.

The issue is actually not related to Astro v4 but Starlight itself since Starlight `v0.14.0`. I submitted a [PR](https://github.com/withastro/starlight/pull/1175) to  attempt to fix the issue and also #11.

This is currently tracked in #14 so I'll close this one but I'll make sure to add updates to the other one.

**Closed by HiDeoo** 2023-12-12 19:34 UTC
