### ISSUE TITLE
Display sidebar when viewing OpenApi docs

### ISSUE THREAD

**Issue by Fruetel** [HiDeoo/starlight-openapi#11] opened 2023-10-11 16:19 UTC
### Is your feature request related to a problem?

When visiting a page generated by starlight-openapi (e.g. https://starlight-openapi.vercel.app/api/petstore/operations/addpet/) , the sidebar disappears. My only option to view another page is to navigate with the back button first. This behavior does not blend in well with the rest of the Starlight page, where the sidebar is typically present all the time.

### Describe the solution you'd like

Ideal solution would be to specify sidebar behavior for starlight-openapi in `astro.config.mjs`. However, the sidebar always being there would be a reasonable default IMO.

**Comment by HiDeoo** [comment] 2023-10-11 16:53
Thanks for jumping in @stefanofa, really appreciate it. :raised_hands:

This is indeed a regression in the latest version as mentioned in the [release notes](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.3.0) due to some changes in Starlight 0.11.0.

I already opened an issue in the Starlight repository to discuss/think how this could be handled but the goal is definitely to bring back the sidebar as it was before.

I'll make sure to ping this issue when a fix is available.

**Comment by edelbalso** [comment] 2023-10-22 14:24
Would be really helpful for anybody looking this up in the future to see the issue as open until it is resolved. I had not realized it was a known issue until I thought to look at closed issues, and I would like to follow this issue so I'm notified when it is fixed.

**Comment by HiDeoo** [comment] 2023-10-23 09:18
> Would be really helpful for anybody looking this up in the future to see the issue as open until it is resolved.

Good point, this was closed by the author and I forgot to reopen it. This is now reopened.

**Comment by stefanofa** [comment] 2023-11-17 11:47
Hey @HiDeoo, absolutely not to stress you out, but do you have any idea when this feature might be released?

**Comment by HiDeoo** [comment] 2023-11-18 08:48
> Hey @HiDeoo, absolutely not to stress you out, but do you have any idea when this feature might be released?

This requires changes into Starlight that I have described in this [discussion](https://github.com/withastro/starlight/discussions/982) and I recently posted my ideas for a fix in this [post](https://github.com/withastro/starlight/discussions/982#discussioncomment-7445632) but so far I didn't get any feedack or suggestions yet.

If I don't get any before I get enough time, I'll switch to making a PR with the changes I described.

**Comment by huijing** [comment] 2024-01-03 07:44
Hello, I've been following along with the related issues and discussions (this turned out to be more complicated than I thought, and saw the latest PR update in https://github.com/withastro/starlight/pull/1175#issuecomment-1871868017. And I was wondering if that goes in, this issue can be resolved as well?

**Comment by HiDeoo** [comment] 2024-01-03 19:50
> And I was wondering if that goes in, this issue can be resolved as well?

Yes, definitely. The PR has a pretty broad scope and try to fix various issues related to custom pages and one of them is indeed having custom content in a custom page using the Starlight layout with the default sidebar.

This [page](https://starlight-git-fork-hideoo-hd-virtual-pages-astrodotbuild.vercel.app/virtual-pages-demo/a/) from the PR preview is an example of a dynamically injected page with some custom content that could be the content of the `starlight-openapi` integration (which will be refactored to a Starlight plugin if the PR is merged) while still having the default Starlight sidebar.

**Comment by huijing** [comment] 2024-01-04 01:21
Oh wow, the possibilities have been greatly expanded. This is amazing work. 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

**Comment by HiDeoo** [comment] 2024-02-18 12:07
Thanks everyone for your patience with this issue. 

[`v0.5.0`](https://github.com/HiDeoo/starlight-openapi/releases/tag/v0.5.0) fixes the issue, e.g. this [demo page](https://starlight-openapi.vercel.app/api/petstore/operations/addpet) which now includes the Starlight sidebar.

**Closed by HiDeoo** 2024-02-18 12:07 UTC

**Comment by stefanofa** [comment] 2024-02-19 09:01
hey @HiDeoo , from behind the scenes I have been following the immense work you have done to make everything possible over the releases of the past few days, and I simply wanted to thank you ❤️
